
name: 'healthcare_dbt_bigquery_data_pipeline'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'healthcare_dbt_bigquery_data_pipeline'

# model-paths: ["healthcare_dbt_bigquery_data_pipeline/models"]
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  healthcare_dbt_bigquery_data_pipeline:
    +materialized: view
