healthcare_dbt_bigquery_data_pipeline:  # Must match "profile" in dbt_project.yml
  outputs:
    dev:
      dataset: dev_healthcare_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service_account.json
      location: europe-west3
      method: service-account
      priority: interactive
      project: healthcare-data-project-442109
      threads: 4
      type: bigquery

    prod:
      dataset: prod_healthcare_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service_account.json
      location: europe-west3
      method: service-account
      priority: interactive
      project: healthcare-data-project-442109
      threads: 4
      type: bigquery

  target: prod
